ENV ETCD_VER=v3.5.21
ENV ETCD_SHA256=adddda4b06718e68671ffabff2f8cee48488ba61ad82900e639d108f2148501c

ENV DOWNLOAD_URL=https://storage.googleapis.com/etcd

RUN curl -L $DOWNLOAD_URL/$ETCD_VER/etcd-$ETCD_VER-linux-amd64.tar.gz -o /tmp/etcd.tar.gz
RUN echo "$ETCD_SHA256 /tmp/etcd.tar.gz" | sha256sum -c -
RUN mkdir /tmp/etcd
RUN tar xzvf /tmp/etcd.tar.gz -C /tmp/etcd --strip-components=1
